-- 0006: prices are charged in US dollars; certificate IDs use the ACM- prefix
-- (e.g. ACM-DEV-2026-00001). IDs are generated by the app, so only the
-- currency default changes here. Existing rows keep whatever currency they
-- were created with.
alter table programmes alter column currency set default 'USD';
